name: Test and Deploy to CloudHub

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Run MUnit Tests with Coverage
        run: mvn clean test -Dcoverage
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}

      - name: Deploy to CloudHub
        if: success()  # Only deploy if tests pass
        run: mvn clean deploy -DmuleDeploy
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
